name: Flutter Web
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Use Flutter Action
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Upgrade Flutter
        run: flutter upgrade

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --release --base-href '/'

      - name: Deploy to GitHub Pages
        run: |
          cd build/web
          git init
          git config --global user.email daothelinh@gmail.com
          git config --global user.name daothelinh
          git add .
          git commit -m "Deploy to GitHub Pages"
          git remote add origin git@github.com:daothelinh/gen_freezed.git
          git branch -m gh-pages
          git push -f origin gh-pages
